package org.ilite.frc.common.types;

import com.flybotix.hfr.codex.CodexOf;

public enum EDriveTrain implements CodexOf<Double> {
  TIME_SECONDS,
  
  DRIVE_MODE,
  DESIRED_LEFT_OUTPUT,
  DESIRED_RIGHT_OUTPUT,
  
  OPEN_LOOP_VOLTAGE_RAMP_RATE,
  
  LEFT_POSITION_TICKS,
  RIGHT_POSITION_TICKS,
  RIGHT_POSITION_ROT,
  LEFT_POSITION_ROT,
  LEFT_POSITION_INCHES,
  RIGHT_POSITION_INCHES,
  
  LEFT_VELOCITY_TICKS,
  RIGHT_VELOCITY_TICKS,
  LEFT_VELOCITY_RPM,
  RIGHT_VELOCITY_RPM,
  LEFT_VELOCITY_FPS,
  RIGHT_VELOCITY_FPS,
  
  OPEN_LOOP_THROTTLE, 
  OPEN_LOOP_TURN,
  OPEN_LOOP_CALC_LEFT_POWER,
  OPEN_LOOP_CALC_RIGHT_POWER,
  
  LEFT_TALON_MASTER_VOLTAGE,
  LEFT_TALON_FOLLOW1_VOLTAGE,
  LEFT_TALON_FOLLOW2_VOLTAGE,
  
  LEFT_TALON_MASTER_CURRENT,
  LEFT_TALON_FOLLOW1_CURRENT,
  LEFT_TALON_FOLLOW2_CURRENT,
  
  RIGHT_TALON_MASTER_VOLTAGE,
  RIGHT_TALON_FOLLOW1_VOLTAGE,
  RIGHT_TALON_FOLLOW2_VOLTAGE,
  
  RIGHT_TALON_MASTER_CURRENT,
  RIGHT_TALON_FOLLOW1_CURRENT,
  RIGHT_TALON_FOLLOW2_CURRENT,
  
  TALON_VBUS,
  TALON_CONTROL_MODE,
}
