package org.ilite.frc.common.config;

import org.ilite.frc.common.types.ELogitech310;

public class DriveTeamInputMap {
  public static final ELogitech310
  
    DRIVER_TURN_AXIS = ELogitech310.RIGHT_X_AXIS,
    DRIVER_THROTTLE_AXIS = ELogitech310.LEFT_Y_AXIS,
    
    DRIVER_SUB_WARP_AXIS = ELogitech310.RIGHT_TRIGGER_AXIS,
    
    DRIVER_SEARCH_CUBE_LEFT_BTN = ELogitech310.L_BTN,
    DRIVER_SEARCH_CUBE_RIGHT_BTN = ELogitech310.R_BTN,
    DRIVER_SEARCH_EXCHANGE_LEFT_BTN = ELogitech310.DPAD_LEFT,
    DRIVER_SERACH_EXCHANGE_RIGHT_BTN = ELogitech310.DPAD_RIGHT,
  
    OPERATOR_CARRIAGE_KICK = ELogitech310.X_BTN,
    OPERATOR_INTAKE_OUT_BTN = ELogitech310.DPAD_DOWN,
    OPERATOR_INTAKE_IN_BTN = ELogitech310.DPAD_UP,
    OPERATOR_OPEN_LOOP_INTAKE_AXIS = ELogitech310.RIGHT_Y_AXIS,
    
    OPERATOR_ELEVATOR_OPEN_LOOP_CONTROL_AXIS = ELogitech310.LEFT_Y_AXIS,
    OPERATOR_ELEVATOR_SETPOINT_GROUND_BTN = ELogitech310.A_BTN,
    OPERATOR_ELEVATOR_SETPOINT_SWITCH_BTN = ELogitech310.B_BTN,
    OPERATOR_ELEVATOR_SETPOINT_TOP_BTN = ELogitech310.Y_BTN
    ;
}
